### PR TITLE
Missing strings for 2.1

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by koehlermichael** [comment]
I hope this pull request can be processed within the next minutes so I can complete the translation now, instead of having to wait until sometime tomorrow…

**Comment by flodolo** [comment]
> I hope this pull request can be processed within the next minutes so I can complete the translation now, instead of having to wait until sometime tomorrow…

It will probably be merged in the next hour or so, but there's plenty of time to translate them in the coming days, so I really wouldn't wait for it to be merged.

**Comment by koehlermichael** [comment]
As I have no idea how much „plenty of time“ I will have in the coming days I’ll just stay around for a little while.

**Comment by koehlermichael** [comment]
Thanks, I just did the translation but I do have an additional question: in the „Email“ string, do I understand the note correctly that what clicking the button „Email“ does is send an e-mail? The test page doesn’t help me. If the meaning of the string is „send e-mail“, is there a way to make sure a longer string properly fits and doesn’t break the layout? (Sorry, I notice that’s two questions.)

**Comment by flodolo** [comment]
That's good question for @thebnich

**Comment by thebnich** [comment]
> in the „Email“ string, do I understand the note correctly that what clicking the button „Email“ does is send an e-mail?

It opens the Mail app with the given mailto: email and subject. So no, it doesn't send the email directly.

> is there a way to make sure a longer string properly fits and doesn’t break the layout?

Longer strings should work OK; iOS will automatically split the buttons to be vertically stacked instead of horizontally stacked (see English "Open App Store" on a 6s as an example).

**Comment by koehlermichael** [comment]
Thanks, in that case the translation probably works.

**Pull request merged**
