### PR TITLE
Cobalt strings

### PR DESCRIPTION
**Pull request by boek**

### CODE REVIEW

**Comment by flodolo** [comment]
Side note: the app version is still 3.5, not sure it matters at this point, and if it should be updated to 3.6

**Comment by boek** [comment]
@flodolo If that's an issue I can get that changed.

**Comment by flodolo** [comment]
> @flodolo If that's an issue I can get that changed.

Localized files will have 3.5 if we expose them like this, if you import them in Focus will the app say somewhere that it's 3.5 instead of 3.6? That's for you folks to discover ;-)

In case, it might be worth to update it to 3.6 to unblock exposing strings, and verify if it's relevant for next time.

P.S. don't forget to update documentation, including this bit if necessary

**Comment by boek** [comment]
@flodolo Good note for adding this to the documentation.

We do use the version number on the about view. Opening a PR on Focus and when that lands I'll have a new l10n PR. Going to close this now.

**Comment by Delphine** [comment]
Thanks guys - catching up with this now. Will wait to see udpated PR then :)

**Pull request closed without merging**
