### PR TITLE
Extract new strings (2023-03-28)

### PR DESCRIPTION
**Pull request by mozilla-pontoon**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Review by Delphine — CHANGES_REQUESTED** [review]
@razvanlitianu Hi! I see this string has already been translated - why we would remove the target in this case?
Also, string exports are usually for all locales, not just en-US.
Please let me know! thanks

**Review by flodolo — COMMENTED** [review]
This is not developers removing translations, this is our infrastructure trying to solve problems they had in the past, where en-US was missing translations in automation.

I'll need to figure out why it didn't add them when it extracted new strings.

**Comment by flodolo** [comment]
Interesting: turns out this was requested for Firefox, not for Focus.
https://github.com/mozilla-l10n/firefoxios-l10n/pull/152

That means that en-US could have untranslated strings, and in this case someone removed the translation from the repository.

Just for sake of consistency, now en-US is always "autotranslated" like in Firefox.

**Comment by Delphine** [comment]
Thanks for clarifying. I saw a recent commit in iOS around that string, and even though it didn't seem directly linked, wasn't sure if it still was somehow

**Pull request closed without merging**
