### PR TITLE
Cobalt strings

### PR DESCRIPTION
**Pull request by boek**

### CODE REVIEW

**Comment by Sdaswani** [comment]
That would be @bkmunar - we have that mac mini he can use to run them: https://github.com/mozilla-mobile/focus-ios/issues/333

**Comment by Delphine** [comment]
Great, thanks for opening that up Susheel

**Comment by boek** [comment]
@bkmunar I want to do this with you!

**Comment by Sdaswani** [comment]
Cool @Delphine maybe you can both remote into the Mac Mini together and create one 'screenshots' account so @boek can use it later.

**Pull request merged**
