### PR TITLE
Included Burgundy strings for Focus

### PR DESCRIPTION
**Pull request by bkmunar**

### CODE REVIEW

**Comment by bkmunar** [comment]
@Delphine @flodolo sorry for the delay

**Comment by Delphine** [comment]
Ah seems like flod commented in the meantime, didn't see that! :)
Flod: If you think we can merge as is, regardless of my comment above, then let's try that. I'll draft my message to localizers in the meantime.

**Comment by flodolo** [comment]
> One thing you may want to check with Stefan though is if it's ok that the tool-id's, tool-names, too-versions, build-nums haven't changed, like they usually do here, because I have no idea (see those at bottom and top of this past PR): 8a08715

They only change when the XCode version used to export the file changes. Good to merge when you're ready.

**Comment by Delphine** [comment]
Thanks for clarifying flod, that's good to know 🦄

**Pull request merged**
