### PR TITLE
Exported new strings to en for Focus

### PR DESCRIPTION
**Pull request by bkmunar**

### CODE REVIEW

**Comment by bkmunar** [comment]
@Delphine @flodolo

**Comment by Delphine** [comment]
We need one PR for all locales, and this is also missing the templates file.
See tips and notes given on last time's PRs here:
* https://github.com/mozilla-l10n/focusios-l10n/pull/8 (that one was wrong for mainly the same reasons)
* https://github.com/mozilla-l10n/focusios-l10n/pull/9 (that's the one we used in the end)

**Comment by Delphine** [comment]
Only looking what's in the PR now. I don't understand why there are so many strings? Something doesn't seem right here. We only discussed adding a few.

**Comment by flodolo** [comment]
The folder is called en-US, you're creating a folder called en…

**Pull request closed without merging**
